name: RegionBattleMod
version: 0.1
author: Vetovius
main: me.vetovius.regionbattlemod.RegionBattleMod
api-version: 1.17
depend: [WorldGuard,Votifier]


commands:
  startregionbattle:
    description: Start the game!
    usage: /startregionbattle
    permission: RegionBattleMod.startregionbattle
  seek:
    description: Seek out a random enemy player, no one can hide!
    usage: /seek while in a battle.
    permission: RegionBattleMod.seek
  tc:
    description: Send a chat to your team only during a battle.
    usage: /tc while in a battle.
    permission: RegionBattleMod.tc
  battleoptout:
    description: Temporarily opt out of battles. Toggleable.
    usage: /battleoptout
    permission: RegionBattleMod.battleoptout
#  chat:
#    description: Toggle which chat channel you are in.
#    usage: /chat s for survival or /chat b for battle. Toggling both chats off will return you to global.
#    permission: RegionBattleMod.chat
  vote:
    description: Vote for our server.
    usage: /vote
    permission: RegionBattleMod.vote
  startpersistentbattle:
    description: Start a persistent battle.
    usage: /startpersistentbattle
    permission: RegionBattleMod.startpersistentbattle
  joinbattle:
    description: Join the battle!
    usage: /joinbattle
    permission: RegionBattleMod.joinbattle
  leavebattle:
    description: Leave the battle!
    usage: /leavebattle
    permission: RegionBattleMod.leavebattle
  createlootchest:
    description: Admin only, for use creating loot chests in battle worlds.
    usage: /createlootchest
    permission: RegionBattleMod.createlootchest