name: RegionBattleMod
version: 0.1
author: Vetovius
main: me.vetovius.regionbattlemod.RegionBattleMod
api-version: 1.17
depend: [WorldGuard]

commands:
  startregionbattle:
    description: Start the game!
    usage: /startregionbattle
    permission: RegionBattleMod.startregionbattle