name: RegionBattleMod
version: 0.1
author: Vetovius
main: me.vetovius.regionbattlemod.RegionBattleMod
api-version: 1.17
depend: [WorldGuard]


commands:
  startregionbattle:
    description: Start the game!
    usage: /startregionbattle
    permission: RegionBattleMod.startregionbattle
  seek:
    description: Seek out a random enemy player, no one can hide!
    usage: /seek while in a battle.
    permission: RegionBattleMod.seek
  tc:
    description: Send a chat to your team only during a battle.
    usage: /tc while in a battle.
    permission: RegionBattleMod.tc