name: RegionBattle
version: 0.1
author: Vetovius
main: me.vetovius.regionbattle.RegionBattle
api-version: 1.17
depend: [WorldGuard,Votifier]


commands:
  startregionbattle:
    description: Start the game!
    usage: /startregionbattle
    permission: RegionBattle.startregionbattle
  seek:
    description: Seek out a random enemy player, no one can hide!
    usage: /seek while in a battle.
    permission: RegionBattle.seek
  tc:
    description: Send a chat to your team only during a battle.
    usage: /tc while in a battle.
    permission: RegionBattle.tc
  battleoptout:
    description: Temporarily opt out of battles. Toggleable.
    usage: /battleoptout
    permission: RegionBattle.battleoptout
#  chat:
#    description: Toggle which chat channel you are in.
#    usage: /chat s for survival or /chat b for battle. Toggling both chats off will return you to global.
#    permission: RegionBattle.chat
  vote:
    description: Vote for our server.
    usage: /vote
    permission: RegionBattle.vote
  startpersistentbattle:
    description: Start a persistent battle.
    usage: /startpersistentbattle
    permission: RegionBattle.startpersistentbattle
  joinbattle:
    description: Join the battle!
    usage: /joinbattle
    permission: RegionBattle.joinbattle
  leavebattle:
    description: Leave the battle!
    usage: /leavebattle
    permission: RegionBattle.leavebattle
  createlootchest:
    description: Admin only, for use creating loot chests in battle worlds.
    usage: /createlootchest
    permission: RegionBattle.createlootchest
  giveplayertoken:
    description: Admin/Server only. Give the specified player a token.
    usage: /giveplayertoken playername
    permission: RegionBattle.giveplayertoken
  opentokenshop:
    description: debugging token shop.
    usage: /opentokenshop
    permission: RegionBattle.opentokenshop
  createtokenshop:
    description: Used for admins to spawn a token shop chest.
    usage: /createtokenshop
    permission: RegionBattle.createtokenshop
  map:
    description: Get the link to dynmap.
    usage: /map
    permission: RegionBattle.map
  discord:
    description: Get the invite link to RegionBattle's discord.
    usage: /discord
    permission: RegionBattle.discord